contigua:
	# Compilando a implementacao da fila
	gcc -c fila_contigua.c -o fila_contigua.o
	
	# Compilando e gerando o executavel
	gcc main.c fila_contigua.o -o main_filaContigua
	
	# Executando
	./main_filaContigua

encadeada:
	# Compilando a implementacao da fila
	gcc -c fila_encadeada.c -o fila_encadeada.o
	
	# Compilando e gerando o executavel
	gcc main.c fila_encadeada.o -o main_filaEncadeada
	
	# Executando
	./main_filaEncadeada

clean:
	rm *.o
	rm main_filaContigua
	rm main_filaEncadeada
